name: basic

on: 
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: print message
        run: |
          echo "Hello, CI with GitHub Actions!."
      - name: Set up Python 3.9
        uses: actions/checkout@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        uses: actions/checkout@v3

  
