name: matrix

on: 
  workflow_dispatch:

jobs:
   my_first_matrix:
     name: my first matrix
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python: [3.7, 3.8, 3.9, 3.10]
         os: [ubuntu-latest, windows-latest]
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: print message
         run: |
          echo "Hello, CI with GitHub Actions!."
       - name: Set up Python ${{ matrix.python }}
         uses: actions/checkout@v4
         with:
          python-version: ${{ matrix.python }}
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Run tests
         run: |
          python -m unittest

      
