name: matrix

on: 
  workflow_dispach:

jobs:
   my_first_matrix:
     name: my first matrix
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python: [3.9, 3.12, 3.11]
         os: [ubuntu-latest, windows-latest]
     steps:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: print message
         run: |
          echo "Hello, CI with GitHub Actions!."
       - name: Set up Python 3.9
         uses: actions/checkout@v4
         with:
          python-version: "3.10"
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       - name: Run tests
         run: |
          python -m unittest

      
